menu:
  首页: / || fas fa-home
  导航||fas fa-list:
    归档: /archives/ || fas fa-archive
    分类: /categories/ || fas fa-folder-open
  统计: / || fas fa-chart-pie
  待办事项: / || fas fa-tasks
  更新日志: / || fas fa-history
  关于: /about/ || fas fa-heart
  小游戏: /game/ || fas fa-gamepad
css_prefix: true  #有些 CSS 并不是所有浏览器都支持，需要增加对应的前缀才会生效
instantpage: false # 当鼠标悬停到链接上超过 65 毫秒时，Instantpage 会对该链接进行预加载，可以提升访问速度
pangu: # 在网页中所有的中文字和半形的英文、数字、符号之间插入空白
  enable: true
  field: site # site/post
subtitle:
  enable: true
  effect: false # 打字效果
  startDelay: 300 # time before typing starts in milliseconds
  typeSpeed: 200 # type speed in milliseconds
  backSpeed: 100 # backspacing speed in milliseconds
  loop: true
  # source 调用第三方服務
  # source: false 关闭调用
  # source: 1  调用一言网的一句話（简体） https://hitokoto.cn/
  # source: 2  调用一句网（简体） http://yijuzhan.com/
  # source: 3  调用今日詩詞（简体） https://www.jinrishici.com/
  # subtitle 会先显示 source , 再显示 sub 的內容
  source: false
  # 如果关闭打字效果，subtitle 只会显示 sub 的第一行文字
  sub:
    - 燃烧心中的火焰，将梦想凌驾于高山。
index_img: /img/home.jpg
archive_img: /img/home.jpg
tag_img: /img/home.jpg
tag_per_img: /img/home.jpg
category_img: /img/home.jpg
category_per_img: /img/home.jpg
preloader: true
index_top_img_height: 700px
wordcount: #文章字数统计
  enable: true
  post_wordcount: true
  min2read: true
  total_wordcount: true
toc: # 文章目录显示位置
  post: true
  page: false
  number: true
  expand: false
  style_simple: false # for post
  scroll_percent: true
aside:
  enable: true
  hide: false
  button: true
  mobile: true     # display on mobile
  position: left   # left or right，决定侧边栏在右边还是在左边
  card_author:
    enable: true
    description: 一个不务正业的测试开发
    button:
      enable: true
      icon: fab fa-github
      text: github
      link: https://github.com/Ones-z
  card_announcement:        #公告
    enable: false
    content: 问题不大
canvas_ribbon:
  enable: true
  size: 150
  alpha: 0.6
  zIndex: -1
  click_to_change: true   #点击鼠标更换彩带
  mobile: false
theme_color:
  enable: true
  main: "#49B1F5"
  paginator: "#00c4b6"
  button_hover: "#FF7242"
  text_selection: "#00c4b6"
  link_color: "#99a9bf"
  meta_color: "#858585"
  hr_color: "#A4D8FA"
  code_foreground: "#F47466"
  code_background: "rgba(27, 31, 35, .05)"
  toc_color: "#00c4b6"
  blockquote_padding_color: "#49b1f5"
  blockquote_background_color: "#49b1f5"
  scrollbar_color: "#49b1f5"
footer:
  owner:
    enable: true
    since: 2023
  custom_text: 一个想做开发的测试 ｜ 一个想做测试的开发
  copyright: false # Copyright of theme and framework
reward:
  enable: true
  QR_code:
    - img: /img/wechat-pay.jpg
      text: 微信
    - img: /img/alipay.jpg
      text: 支付宝
highlight_theme: mac light
highlight_copy: true
highlight_lang: true
highlight_shrink: false
highlight_height_limit: false
code_word_wrap: false
sharejs:
  enable: true
  sites: wechat,qq
post_copyright:
  enable: true
  decode: utf-8
avatar:
  img: /img/favicon.ico
  effect: false
favicon: /img/favicon.ico
social:
  fab fa-weixin: /img/wechat.jpg || WeChat
  fab fa-qq: /img/qq.jpg || QQ
  fas fa-envelope: mailto:2874071013@qq.com || Email
inject: # 插入代码到头部 </head> 之前 和 底部 </body> 之前
  head:
    - <link rel="stylesheet" href="/css/custom.css">
  bottom:
mask: # 为 header 或 footer 添加黑色半透遮罩
  header: true
  footer: true

nav:
  logo: # image
  display_title: true
  fixed: true  # fixed navigation bar

# 文章底部
copy: # 复制配置，开启后复制内容后会加入版权信息
  enable: true
  copyright:
    enable: true
    limit_count: 50

hr_icon: # 水平分隔线图标设置，带个小剪刀图标
  enable: true
  icon: # the unicode value of Font Awesome icon, such as '\3423'
  icon-top:

beautify: # 列表项前是否加图标
  enable: false
  field: post # site/post
  title-prefix-icon:  '\f0c1'
  title-prefix-icon-color: '#F47466'

  # 显示评论
newest_comments:
  enable: true
  sort_order: # Don't modify the setting unless you know how it works
  limit: 6
  storage: 10 # unit: mins, save data to localStorage
  avatar: true

local_search: # 本地搜索
  enable: true
  preload: false
  top_n_per_article: 1
  unescape: false
  CDN:

lazyload: # Lazyload (圖片懶加載)
  enable: false
  field: site # site/post
  placeholder:
  blur: false